In [1]:
import numpy as np

In [3]:
array1 = np.ones(4);array1

array([1., 1., 1., 1.])

In [6]:
array2 = np.arange(15);array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
array_conc = np.concatenate((array1, array2));array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

In [11]:
#join de arrays

a=np.ones((3,3))
b=np.zeros((3,3))

In [12]:
print(a);print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [17]:
a=np.array([0,1,2])
b=np.array([3,4,5])
c=np.array([6,7,8])

In [19]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [20]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
array3 = np.arange(16).reshape((4,4));array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
[array3_pl,array3_p2]= np.hsplit(array3,2)

In [25]:
array3_pl

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [28]:
[array3_pl,array3_p2]= np.vsplit(array3,2)

In [29]:
array3_pl

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
#Matrizes Numpy
mat1 = np.matrix("1,2,3;4,5,6");mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [34]:
mat2 = np.matrix([[1,2,3],[4,5,6]]);mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [40]:
a= np.array([[1,2],[3,4]]);a

array([[1, 2],
       [3, 4]])

In [41]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [42]:
A =np.mat(a)

In [43]:
A*A

matrix([[ 7, 10],
        [15, 22]])

In [44]:
#multiplicando um array como se fosse uma múltiplicação de matrizes
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [45]:
#convertendo uma matriz em um array
mat5 = np.asmatrix(a);mat5

matrix([[1, 2],
        [3, 4]])

In [46]:
mat5*mat5

matrix([[ 7, 10],
        [15, 22]])

In [47]:
#convertendo uma matriz para array
array2 = np.asarray(mat5);array2


array([[1, 2],
       [3, 4]])

In [48]:
array2*array2

array([[ 1,  4],
       [ 9, 16]])

In [51]:
array1 = np.random.randint(0,50,20);array1

array([ 7, 39,  5, 30, 25, 29, 21, 26, 40, 30,  8,  4, 27, 48, 36, 29, 26,
       30,  8, 42])

In [52]:
def calc_func(num):
    if num <10:
        return num **3
    else:
        return num **2

In [53]:
#não é possível aplicar diretamente uma função a um array numpy para isso é necessário vetorizar a função
calc_func(array1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
v_calc_func = np.vectorize(calc_func)

In [55]:
type (v_calc_func)

numpy.vectorize

In [56]:
v_calc_func(array1)

array([ 343, 1521,  125,  900,  625,  841,  441,  676, 1600,  900,  512,
         64,  729, 2304, 1296,  841,  676,  900,  512, 1764])

In [58]:
#com a função mpa não é necessário vetorizar
list(map(calc_func, array1))

[343,
 1521,
 125,
 900,
 625,
 841,
 441,
 676,
 1600,
 900,
 512,
 64,
 729,
 2304,
 1296,
 841,
 676,
 900,
 512,
 1764]

In [61]:
#da mesma forma com list comprehension
[calc_func(x) for x in array1]

[343,
 1521,
 125,
 900,
 625,
 841,
 441,
 676,
 1600,
 900,
 512,
 64,
 729,
 2304,
 1296,
 841,
 676,
 900,
 512,
 1764]

In [62]:
import pandas as pd

In [65]:
serie1 = pd.Series(np.arange(26));serie1

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [66]:
import string

In [67]:
lcase = string.ascii_lowercase
ucase = string.ascii_uppercase
print(lcase,ucase)

abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ


In [69]:
#convertendo em lista
lcase = list(lcase)
ucase = list(ucase)
print(lcase,ucase)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']


In [70]:
serie1.index = lcase;serie1

a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32

In [71]:
#slice pelo índice 
serie1['f':'r']

f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
dtype: int32

In [72]:
import matplotlib.pyplot as plt
%matplotlib inline

In [77]:
np.random.seed(784)

In [78]:
array = np.random.randint(1,30,40)

In [79]:
array1

array([ 7, 39,  5, 30, 25, 29, 21, 26, 40, 30,  8,  4, 27, 48, 36, 29, 26,
       30,  8, 42])

In [76]:
dados = pd.Series(array1);dados

0      7
1     39
2      5
3     30
4     25
5     29
6     21
7     26
8     40
9     30
10     8
11     4
12    27
13    48
14    36
15    29
16    26
17    30
18     8
19    42
dtype: int32

In [80]:
#Usando o numpy com valores NaN
array1 = np.array([1,2,3,np.nan]);array1

array([ 1.,  2.,  3., nan])

In [82]:
array1.mean()

nan

In [84]:
#Usando o pandas com valores NaN
serie1 = pd.Series([1,2,3,np.nan]);serie1

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [85]:
serie1.mean()


2.0

In [1]:
import pandas as pd


In [ ]:
#Dados originais
dados1 = {'disciplina_id': ['1','2','3','4','5'],
          'nome': ['Bernardo','Alan', 'Mateus','Ivo','Gerson'],
          'sobrenome':['Anderson', 'Teixeira','Amoedo','Trindade','Vargas']}
#criação do dataframe
df_a = pd.DataFrame(dados2,columns = ['disciplina_id','nome','sobrenome'])
df_a

In [ ]:
#Dados originais
dados2 = {'disciplina_id': ['4','5','6','7','8'],
          'nome': ['Roberto','Mariana', 'Ana','Marcos','Maria'],
          'sobrenome':['Sampaio', 'Fernandes','Arantes','Menezes','Martins']}
#criação do dataframe
df_b = pd.DataFrame(dados2,columns = ['disciplina_id','nome','sobrenome'])
df_b

In [ ]:
#Dados originais
dados3 = {'disciplina_id': ['1','2','3','4','5','6','7','8','9','10','11'],
          'teste_id': [81,75,75,71,76,84,95,61,57,90]}

#criação do dataframe
df_n = pd.DataFrame(dados3,columns = ['disciplina_id','teste_id'])
df_n